language: python
python: 3.3
env:
- TOX_ENV=py33
- TOX_ENV=py34
- TOX_ENV=py35
- TOX_ENV=py36
- TOX_ENV=py37
- TOX_ENV=pypy3
script: tox -e $TOX_ENV
install: pip install -r tests_requirements.txt && pip install .
