language: python
python:
  - "3.2"
  - "3.3"
script: nosetests -w tests/ssyncer
before_install:
  svn checkout http://stagger.googlecode.com/svn/trunk/ stagger &&
  patch stagger/setup.py stagger-setup.patch &&
  pip install stagger/
install: pip install .
